using System.Text;
using WebAppMulti.Models.Corqs;

public class ReactQueryMapGenerator
{
    public string Generate(List<ApiDefinition> apis)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// AUTO-GENERATED by CORQS schema — do not edit manually");
        sb.AppendLine("export const QUERY_MAP = [");

        foreach (var api in apis.Where(a => a.DataRoute != null))
        {
            var dr = api.DataRoute!;
            var type = dr.Type != null ? $"\"{dr.Type}\"" : "null";
            var idParam = dr.IdParam != null ? $", idParam: \"{dr.IdParam}\"" : "";
            var typeParam = dr.TypeParam != null ? $", typeParam: \"{dr.TypeParam}\"" : "";
            sb.AppendLine($"  {{ resource: \"{dr.Resource}\", type: {type}, action: \"{api.Name}\"{idParam}{typeParam} }},");
        }

        sb.AppendLine("];");
        return sb.ToString();
    }
}
