using System.Text;
using WebAppMulti.Models.Corqs;

public class ReactQueryMapGenerator
{
    public string Generate(List<ApiDefinition> apis)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// AUTO-GENERATED by CORQS schema — do not edit manually");

        // CORQS APIs (POST /api/corqs)
        sb.AppendLine("export const QUERY_MAP = [");
        foreach (var api in apis.Where(a => a.Type != "get"))
        {
            sb.AppendLine("  {");
            sb.AppendLine($"    resource: \"{api.Name}\",");
            sb.AppendLine($"    action: \"{api.Name}\",");

            var routeParams = BuildRouteParams(api);
            if (routeParams != null)
                sb.AppendLine($"    routeParams: {routeParams},");

            if (api.Actions != null && api.Actions.Any())
            {
                sb.AppendLine("    actions: [");
                foreach (var action in api.Actions)
                    sb.AppendLine($"      {{ label: \"{action.Label}\", route: \"{action.Route}\" }},");
                sb.AppendLine("    ],");
            }

            if (api.Enrichments != null && api.Enrichments.Any())
            {
                sb.AppendLine("    enrichments: [");
                foreach (var enrichment in api.Enrichments)
                    sb.AppendLine($"      {{ column: \"{enrichment.Column}\", sourceColumn: \"{enrichment.SourceColumn}\", path: \"{enrichment.Path}\" }},");
                sb.AppendLine("    ],");
            }

            sb.AppendLine("  },");
        }
        sb.AppendLine("];");

        sb.AppendLine();

        // Direct GET endpoints
        sb.AppendLine("export const DIRECT_ENDPOINTS = [");
        foreach (var api in apis.Where(a => a.Type == "get"))
        {
            sb.AppendLine("  {");
            sb.AppendLine($"    name: \"{api.Name}\",");
            sb.AppendLine($"    url: \"{api.Route}\",");
            sb.AppendLine($"    returns: \"{api.Returns ?? "json"}\",");

            if (api.Params != null && api.Params.Any())
            {
                var keys = string.Join(", ", api.Params.Keys.Select(k => $"\"{k}\""));
                sb.AppendLine($"    params: [{keys}],");
            }

            sb.AppendLine("  },");
        }
        sb.AppendLine("];");

        return sb.ToString();
    }

    private string? BuildRouteParams(ApiDefinition api)
    {
        // Array form — inferred from schema params block (state params)
        if (api.Params != null && api.Params.Any())
        {
            var keys = string.Join(", ", api.Params.Keys.Select(k => $"\"{k}\""));
            return $"[{keys}]";
        }

        // Object form — single URL slot mapped via dataRoute.IdParam
        //if (api.DataRoute?.IdParam != null)
        //    return $"{{ id: \"{api.DataRoute.IdParam}\" }}";

        return null;
    }

}
