using System.Text;
using WebAppMulti.Models.Corqs;

public class ReactQueryMapGenerator
{
    public string Generate(List<ApiDefinition> apis)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// AUTO-GENERATED by CORQS schema — do not edit manually");
        sb.AppendLine("export const QUERY_MAP = [");

        //foreach (var api in apis.Where(a => a.DataRoute != null))
        foreach (var api in apis)
        {
            sb.AppendLine("  {");
            sb.AppendLine($"    resource: \"{api.Name}\",");
            sb.AppendLine($"    action: \"{api.Name}\",");

            var routeParams = BuildRouteParams(api);
            if (routeParams != null)
                sb.AppendLine($"    routeParams: {routeParams}");

            sb.AppendLine("  },");
        }

        sb.AppendLine("];");
        return sb.ToString();
    }

    private string? BuildRouteParams(ApiDefinition api)
    {
        // Array form — inferred from schema params block (state params)
        if (api.Params != null && api.Params.Any())
        {
            var keys = string.Join(", ", api.Params.Keys.Select(k => $"\"{k}\""));
            return $"[{keys}]";
        }

        // Object form — single URL slot mapped via dataRoute.IdParam
        //if (api.DataRoute?.IdParam != null)
        //    return $"{{ id: \"{api.DataRoute.IdParam}\" }}";

        return null;
    }

}
