// AUTO-GENERATED by CORQS schema — do not edit manually
export const QUERY_MAP = [
    {
        resource: "searchCases",
        action: "searchCases",
        actions: [
            { label: "Open", route: "/cases/{caseId}" },
        ],
        enrichments: [
            { column: "patientName", sourceColumn: "jsonDocumentId", path: "patient.name" },
        ],
    },
    {
        resource: "Case_GetDocuments",
        action: "Case_GetDocuments",
        routeParams: ["caseId"],
        actions: [
            { label: "Open", route: "/docviewer/{documentId}" },
        ],
    },
    {
        resource: "getBooks22",
        action: "getBooks22",
        routeParams: ["caseId", "workbookQId"],
        actions: [
            { label: "Open", route: "/docviewer/{documentId}" },
        ],
    },
    {
        resource: "getCalendar",
        action: "getCalendar",
        routeParams: ["month"],
    },
    {
        resource: "getServerTime",
        action: "getServerTime",
    },
    {
        resource: "getUser",
        action: "getUser",
    },
    {
        resource: "activeCases",
        action: "activeCases",
    },
    {
        resource: "getBooks",
        action: "getBooks",
    },
    {
        resource: "getBook",
        action: "getBook",
        routeParams: ["caseId", "fileName"],
    },
    {
        resource: "getWorkbooksByCase",
        action: "getWorkbooksByCase",
        routeParams: ["caseId"],
        actions: [
            { label: "Open", route: "/data/getBook/{fileName}/{caseId}" },
        ],
    },
    {
        resource: "initializeWorkbooks",
        action: "initializeWorkbooks",
    },
    {
        resource: "getDocumentList",
        action: "getDocumentList",
        routeParams: ["documentType", "caseId", "isActive"],
        actions: [
            { label: "Open", route: "/docviewer/{documentId}" },
        ],
    },
    {
        resource: "getInvoiceDetails",
        action: "getInvoiceDetails",
        routeParams: ["invoiceId"],
    },
    {
        resource: "getInvoices",
        action: "getInvoices",
        routeParams: ["caseId", "status", "fromDate", "toDate", "sessionId"],
        actions: [
            { label: "Open", route: "/invoice/{invoiceId}" },
        ],
    },
];

export const DIRECT_ENDPOINTS = [
    {
        name: "getDocument",
        url: "/api/getDocument",
        returns: "file",
        params: ["docId", "caseId", "workbookQId", "sessionId", "documentType"],
    },
    {
        name: "wfRunReport",
        url: "/api/wfRunReport",
        returns: "html",
        params: ["docId"],
    },
];
