// AUTO-GENERATED by CORQS schema — do not edit manually
export const QUERY_MAP = [
    {
        resource: "searchCases",
        action: "searchCases",
    },
    {
        resource: "getCalendar",
        action: "getCalendar",
        routeParams: ["month"]
    },
    {
        resource: "getServerTime",
        action: "getServerTime",
    },
    {
        resource: "getUser",
        action: "getUser",
    },
    {
        resource: "activeCases",
        action: "activeCases",
    },
    {
        resource: "getBooks",
        action: "getBooks",
    },
    {
        resource: "getBook",
        action: "getBook",
        routeParams: ["caseId", "fileName"]
    },
    {
        resource: "getWorkbooksByCase",
        action: "getWorkbooksByCase",
    },
    {
        resource: "initializeWorkbooks",
        action: "initializeWorkbooks",
    },
];
